# Generated by Django 5.2.4 on 2025-08-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': '测试',
                'verbose_name_plural': '测试',
                'db_table': 'test',
            },
        ),
    ]
